# Generated by Django 4.2.2 on 2023-07-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_alter_complaint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
